# Generated by Django 4.2.7 on 2023-12-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_system_app', '0002_alter_user_identity_document_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='credit',
            name='credit_term',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credit',
            name='start_payment_date',
            field=models.DateField(auto_now=True),
        ),
    ]
