# Generated by Django 4.2.7 on 2023-12-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_system_app', '0003_remove_credit_payment_date_credit_credit_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secure_code',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
