# Generated by Django 4.2.7 on 2023-12-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_system_app', '0004_user_secure_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='current_sum',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
