# Generated by Django 4.2.7 on 2023-12-09 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_system_app', '0005_categories_current_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank_system_app.transactions'),
        ),
    ]
