# Generated by Django 4.2.7 on 2023-12-09 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_system_app', '0006_categories_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transactions',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_system_app.categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='current_sum',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10),
            preserve_default=False,
        ),
    ]
